server:
  port: ${ENV_PORT:9082}
  servlet:
    context-path: ${ENV_CTX_PATH:/sample-tilt}
spring:
  profiles:
    active: ${ENV:dev}
  config:
    use-legacy-processing: true
  application:
    name: sample-tilt
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - loggers
  endpoint:
    health:
      show-details: always